import jsPDFInvoiceTemplate, { OutputType } from "jspdf-invoice-template";
import QRCode from 'qrcode';
import { generateDocumentHash } from './hashGenerator';

export async function generateWageSlipPDF(wageData) {
  // Generate Cryptographic Hash if not provided
  if (!wageData.hash_id) {
    wageData.hash_id = generateDocumentHash({
      worker_name: wageData.worker_name,
      site_name: wageData.site_name,
      period: wageData.period,
      net_pay: wageData.net_pay
    });
  }

  // Generate QR
  const verifyUrl = `${window.location.origin}/verify/${wageData.hash_id}`;
  const qrDataUrl = await QRCode.toDataURL(verifyUrl, { margin: 1 });

  const props = {
    outputType: OutputType.Blob,
    returnJsPDFDocObject: true,
    fileName: `WageSlip_${wageData.worker_name}_${wageData.period}`,
    orientationLandscape: false,
    compress: true,
    logo: {
      src: qrDataUrl,
      type: 'PNG', 
      width: 30,
      height: 30,
      margin: {
        top: 0,
        left: 0
      }
    },
    business: {
      name: "KAAM Setu - Verified Income Passport",
      address: "Tamper-Proof Wage Slip",
      phone: `Hash: ${wageData.hash_id.substring(0, 16)}...`,
      email: "Scan QR to verify document integrity cryptographically",
    },
    contact: {
      label: "Worker Details:",
      name: wageData.worker_name,
      address: `Site: ${wageData.site_name}`,
      phone: `Contractor: ${wageData.contractor_name}`,
    },
    invoice: {
      label: "Wage Period: ",
      num: wageData.period,
      invDate: `Generated: ${new Date().toLocaleDateString()}`,
      headerBorder: false,
      tableBodyBorder: false,
      header: [
        { title: "#", style: { width: 10 } }, 
        { title: "Description", style: { width: 80 } }, 
        { title: "Amount (INR)" }
      ],
      table: [
        [1, `Days Worked (${wageData.days_worked} days)`, wageData.base_pay],
        [2, `Overtime`, wageData.overtime],
        [3, `Advances Given`, `-${wageData.advances}`],
        [4, `Other Deductions`, `-${wageData.deductions}`],
      ],
      invTotalLabel: "Net Pay:",
      invTotal: `Rs. ${wageData.net_pay}`,
      invCurrency: "INR",
      row1: {
        col1: 'Daily Wage Rate:',
        col2: `Rs. ${wageData.daily_wage}`,
        style: { fontSize: 10 }
      },
      row2: {
        col1: 'Gross Pay:',
        col2: `Rs. ${wageData.gross_pay}`,
        style: { fontSize: 10 }
      }
    },
    footer: {
      text: "This document is generated by KAAM Setu and is cryptographically verifiable.",
    },
    pageEnable: true,
    pageLabel: "Page ",
  };

  const pdfObject = jsPDFInvoiceTemplate(props);
  return pdfObject.blob;
}
